version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra_lab
    ports:
      - "9042:9042"    # CQL
      - "7199:7199"
      - "7000:7000"
      - "7001:7001"
      - "9160:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=solar-cluster
      - CASSANDRA_NUM_TOKENS=16
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: [ "CMD", "bash", "-c", "cqlsh -e 'describe keyspaces' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 12
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./scripts:/workspace

  lab:
    build: .
    container_name: solar_lab_py
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    command: tail -f /dev/null
    ports:
      - "8888:8888"

volumes:
  cassandra_data: